experiments:
  controller:
    results_folder: /data/results
  hosts:
    - host: "sgx13.dima.tub"
      base_path: /local-ssd/gdusella-ldap
      public_key_path: ssh/keys/rasvec-docker.pub
  data: # if undefined cmd parameters can be used to manually define data
    raster: /data/PRISM_ppt_stable_4kmD2_20210901_crs83
    vector: /data/ne_10m_admin_1_states_provinces
  workload:
    get: 
      vector:
        - name
      raster: 
        - sval:
            aggregations:
              - avg
              - max
              - min
              - count
              - sum
    join:
      table1: vector
      table2: raster
      condition: intersect(raster, vector)
    condition: 
      vector: 
        - iso_a2 = 'US'
      raster:
        - sval >= 0
    group:
      vector: 
        - name
    order:
      vector: 
        - name
  parameters:
    vectorize_format:
      - shp
      - geojson
    vector_format:
      - shp
#    vectorize_type:
#      - points
    align_to_crs: both
    align_crs_at_stage:
      - preprocess
      - execute
  systems:
    - name: postgis
      port: 25432
#    - name: omnisci
#      port: 6274
#    - name: rasdaman
#      port: 8080
    - name: sedona