config:
  controller:
    results_folder: /data/results
    results_db: /data/results.db
  hosts:
    - host: "sgx10.dima.tub"
      base_path: /local-ssd/gdusella-ldap
      public_key_path: ~/.ssh/lrv.pub
