version: "3.9"
services:

  benchi:
    build:
      context: .
      target: benchi
    volumes:
      - ./benchi/config:/hub/config
      - ./benchi/recipes:/hub/recipes
      - ./data:/data
      - ./benchi/ssh/config:/hub/ssh/config
      - ./benchi/ssh/keys:/hub/ssh/keys
    environment:
      PYTHONUNBUFFERED: 1
    command:
      - python
      - benchi.py
      - --config
      - config/controller_config.yaml
      - --experiment
      - recipes/county-glc.yaml
      - start

