version: "3.9"
services:
  gdal_env:
    build:
      context: .
      target: base
    volumes:
      - .:/hub
      - ~/git/master-raster-vector/data:/data
    tty: true
    environment:
      PYTHONPATH: /hub
#      PERSONAL_TOKEN: ${PERSONAL_TOKEN}
#      TRIGGER_TOKEN: ${TRIGGER_TOKEN}
