version: "3.9"
services:

  benchi:
    build:
      context: .
      target: benchi
    #image: ghcr.io/polydbms/raven:CHOOSECORRECTVERSION
    volumes:
      - ./config:/hub/config
      - ./recipes:/hub/recipes
      - ./data:/data
      - ./ssh/config:/hub/ssh/config
      - ./ssh/keys:/hub/ssh/keys
    environment:
      PYTHONUNBUFFERED: 1
    command:
      - python
      - benchi.py
      - --config
      - config/controller_config.yaml
      - --experiment
      - recipes/county-glc.yaml
      - start

