version: '2.1'

services:

  sedona:
    image: ghcr.io/polydbms/sedona:1.5.1-3.5.0
    volumes:
      - ../../data:/data
      - ../../config:/config
    user: root
    environment:
      - GRANT_SUDO=yes
    tty: true
