version: '2.1'

services:

  sedona:
    image: registry.gitlab.com/zergar/benchi/sedona:3.3.1-2
    volumes:
      - ../../data:/data
      - ../../config:/config
    user: root
    environment:
      - GRANT_SUDO=yes
    tty: true
