version: '2.1'

services:

  sedona:
    image: laertnuhu/sedona
    volumes:
      - ../../data:/data
      - ../../config:/config
    user: root
    environment:
      - GRANT_SUDO=yes
    tty: true
