version: '2.1'

services:

  beast:
    image: ghcr.io/polydbms/beast:0.10.0-3.5.0
    volumes:
      - ../../data:/data
      - ../../config:/config
    user: root
    environment:
      - GRANT_SUDO=yes
    tty: true
